branch-defaults:
  main:
    environment: Dogventure-BE-dev
deploy:
  artifact: build/libs/dogweb-0.0.1-SNAPSHOT.jar
environment-defaults:
  Dogventure-BE-dev:
    branch: null
    repository: null
global:
  application_name: Dogventure-BE
  default_ec2_keyname: dogventure-eb2
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
